### ISSUE TITLE
Connection Error: Unable to Connect to Minecraft Server

### ISSUE THREAD

**Issue by DavidFrings** [Sonic2423/NeoForwarding#4]
### **Can anyone help me with this issue?**

I might be missing something, but when I try to connect to my server, I encounter this error:

![image](https://github.com/user-attachments/assets/cf967b09-0f14-4088-b4d9-141daa769382)

In the Velocity console, this message appears:

![2024_08_17_23_24_01_privatgames net](https://github.com/user-attachments/assets/e5dcdd1f-beb9-49f2-9b89-9a0b0fcfe563)

And in the Modpack console, I see the following:

![image](https://github.com/user-attachments/assets/51be5545-e376-441d-8cc5-bec3e5989a80)

I'm using Enigmatica 10, and I suspect the Minecraft error is occurring because it's trying to connect to my fallback server.

What could I be doing wrong?

Any help would be greatly appreciated!

**Comment by Sonic2423** [comment]
Cant reproduce.
The client receives only the last tried server message (in velocity.toml try list) .
It is probably the same max known packs issue again (that is because of velocity enforcing vanilla pack limits).
See FAQ on the modrinth NeoForwarding mod page.
Let me know if this fixes your issue. MfG :).
![grafik](https://github.com/user-attachments/assets/a18b59c5-7078-4cbf-b714-6f883585fd08)
